version: '3.8'
services:
  warhammer40k-database:
    image: postgres:latest
    container_name: Warhammer40k-Database
    environment:
      POSTGRES_USER: warhammer40k
      POSTGRES_PASSWORD: warhammer40k
      POSTGRES_DB: warhammer40kDocker
    ports:
      - "32768:5432"
    volumes:
      - database-warhammer40k:/var/lib/postgresql/data

  warhammer40k-api:
    image: openjdk:17-jdk-slim
    container_name: Warhammer40k-API
    ports:
      - "32769:8080"
    volumes:
      - ./build/libs:/app
    command: [ "java", "-jar", "/app/warhammer40k-1.0.0-SNAPSHOT.jar" ]
    depends_on:
      - warhammer40k-database

volumes:
  database-warhammer40k:
    external: true
